
services:
  # AgentSociety 应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentsociety_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    command: agentsociety ui --config-base64 eyJhZGRyIjogIjAuMC4wLjA6ODA4MCJ9

  # PostgreSQL 数据库服务
  db:
    image: postgres:16
    container_name: agentsociety_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO 对象存储服务 (S3 兼容)
  minio:
    # 把不可用的 RELEASE 标签改为 latest，或者指定一个存在的 Release
    image: minio/minio:latest
    container_name: agentsociety_minio
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      # 如果你安装了 mc 客户端，可保留；否则也可以改成 curl
      test: [ "CMD", "mc", "alias", "set", "local", "http://localhost:9000", "${MINIO_ROOT_USER}", "${MINIO_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  minio_data:
